language: bash
arch: amd64          # optional, this is default, routes to a full VM
os: linux            # optional, this is default
dist: focal          # or bionic | xenial | trusty | precise with xenial as default
addons:
  apt:
    packages:
      - docker-ce
      
sudo: required
services:
  - docker

env:
  global:
    - COMPOSE_FILES="-f examples/develop/docker-compose.yml"
before_install:
 - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
 - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
 - sudo apt-get update
 - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
 - docker --version
 - docker-compose --version

script:
 - docker-compose ${COMPOSE_FILES} build
 - docker-compose ${COMPOSE_FILES} -p eggnetdockercompose up -d
 - count=0; until docker logs eggnetdockercompose_site_1 | grep "Server running..." &> /dev/null || (( count++ > 12 )); do echo "Waiting $count"; sleep 5; done
 - docker logs eggnetdockercompose_site_1
 - docker logs eggnetdockercompose_site_1 | grep "Server running..." &> /dev/null
