language: bash
arch: amd64          # optional, this is default, routes to a full VM
os: linux            # optional, this is default
dist: focal          # or bionic | xenial | trusty | precise with xenial as default
addons:
  apt:
    sources:
      - sourceline: 'ppa:chris-lea/redis-server'
    packages:
    - redis-tools
    - redis-server
    
sudo: required
services:
  - docker

env:
  global:
    - COMPOSE_FILES="-f examples/develop/docker-compose.yml"
before_install:
 - docker --version
 - docker-compose --version

script:
 - docker-compose ${COMPOSE_FILES} build
 - docker-compose ${COMPOSE_FILES} -p eggnetdockercompose up -d
 - count=0; until docker logs eggnetdockercompose_site_1 | grep "Server running..." &> /dev/null || (( count++ > 12 )); do echo "Waiting $count"; sleep 5; done
 - docker logs eggnetdockercompose_site_1
 - docker logs eggnetdockercompose_site_1 | grep "Server running..." &> /dev/null
