version: "3.9"
services:
  eggnet-master:
    build: 
      # PATH OF Dockerfile 
      context: ../..
      args:
        ### The variables for the build of the image
        # OS Debian Version:
        - OS_NAME=debian
        # OS Version:
        - OS_VERSION=stable-slim
        # User and group unix
        - UNIX_UID=1000
        - UNIX_GID=1000
        - UNIX_USER=debian
        - UNIX_GROUP=debian
        ### The compilation options for eggdrop
        # Choice of eggdrop version
          # Branch/tags: develop, 1.9.1, ..
        - EGG_VERSION=develop
        # The URL of the git repository
        - EGG_URL=https://github.com/eggheads/eggdrop.git
        # Arguments for the ./configure eggdrop command
        - EGG_CONFIGURE_ARGS=--disable-ipv6 --enable-tls --enable-tdns
        # Eggdrop modules not to be compiled
        - EGG_DISABLE_MODULES=woobie uptime ident assoc seen filesys compress share transfer twitch
        - PKG_EXTRA_BUILDER
        - PKG_EXTRA_RUNTIME=mysqltcl tcllib tcl-tls
    environment:
      ### EGGDROP CONFIGURATION
        # Bot irc Nickname
      - EGG_NICK=EggNet-Master
        # Your Nickname IRC
      - EGG_OWNER=ZarTek
      # This eggdrop is the master?
        # 1 : HUB
        # 0 : LEAF
        # Default : LEAF
      - EGG_ISMASTER=1
      ### IRCD CONFIGURATION
      - IRC_NETNAME=Libera
      - IRC_SERVER=irc.libera.chat
        # IRCD PORT 
          # without ssl: 6667
          # with ssl: +6697
      - IRC_PORT=+6697
        # PASSORD OF THE IRCD
      - IRC_PASSWORD=
        # List of salons to join
          # Example: #MyChannel1,#MyChannel2
      - IRC_CHANNELS=#docker-eggnet
      ### PARTYLINE CONFIGURATION
      - PPL_USER=eggnet
      - PPL_PASS=rootegg
    container_name: "eggnet-master"
    restart: always
    volumes:
      - ${EGG_DIR_DATA:-./EggNet_DATADIR}/:/eggdrop-data/data:rw
    ports:
      - "9090:3333"
    networks:
      - eggnet-network
  # With fewer example variables:
  eggnet-slave:
    build: 
      # PATH OF Dockerfile 
      context: ../..
      args:
        ### The compilation options for eggdrop
        # Choice of eggdrop version
          # Branch/tags: develop, 1.9.1, ..
        # The URL of the git repository
        - PKG_EXTRA_RUNTIME=tcllib
    environment:
        # Bot irc Nickname
      - EGG_NICK=EggNet-Slave
      ### EGGDROP CONFIGURATION
        # Bot irc Nickname
        # Your Nickname IRC
      - EGG_ISMASTER=0
      ### IRCD CONFIGURATION
      - IRC_NETNAME=Libera
      - IRC_SERVER=irc.libera.chat
      - IRC_PORT=6667
      ### PARTYLINE CONFIGURATION
      - PPL_USER=eggnet
      - PPL_PASS=rootegg
    container_name: "eggnet-slave"
    restart: always
    volumes:
      - ${EGG_DIR_DATA:-./EggNet_DATADIR}/:/eggdrop-data/data:rw
    ports:
      - "9091:3333"
    networks:
      - eggnet-network
networks:
  eggnet-network:
    driver: bridge
