version: "3.9"
services:
  eggdrop-targate-ng:
    build:
      context: /home/docker/_images/eggdrop
      tags:
        - "eggdrop-targate-ng:latest"
      args:
        ### The variables for the build of the image
        # OS Debian Version: (default: debian)
        - OS_NAME=${OS_NAME:-debian}
        # OS Version: (default: stable-slim)
        - OS_VERSION=${OS_VERSION:-stable-slim}
        # User and group unix
        - UNIX_UID=${UNIX_UID:-1000}
        - UNIX_GID=${UNIX_GID:-1000}
        - UNIX_USER=${UNIX_USER:-debian}
        - UNIX_GROUP=${UNIX_GROUP:-debian}
        ### The compilation options for eggdrop
        # Choice of eggdrop version
          # Branch/tags: develop, 1.9.1, ..
        - EGG_VERSION=${EGG_VERSION:-develop}
        # The URL of the git repository
        - EGG_URL=${EGG_URL:-https://github.com/eggheads/eggdrop.git}
        # Arguments for the ./configure eggdrop command
        - EGG_CONFIGURE_ARGS=${EGG_CONFIGURE_ARGS:--disable-ipv6 --enable-tls --enable-tdns}
        # Eggdrop modules not to be compiled
        - EGG_DISABLE_MODULES=${EGG_DISABLE_MODULES:-twitch transfer share compress filesys woobie seen assoc ident uptime ctcp notes}
        - PKG_EXTRA_BUILDER
        - PKG_EXTRA_BUILDER=${PKG_EXTRA_BUILDER:-}
        - PKG_EXTRA_RUNTIME=${PKG_EXTRA_RUNTIME:-mysqltcl tcllib tcl-tls}
    environment:
      ### EGGDROP CONFIGURATION
        # Bot irc Nickname
      - EGG_NICK=Docker-Egg-???
        # Your Nickname IRC
      - EGG_OWNER=ZarTek
        # Your Username IRC
      - EGG_USERNAME=EggNet
      - EGG_SASL=1
      - EGG_CAPS=1
      # This eggdrop is the master?
        # 1 : HUB
        # 0 : LEAF
        # Default : LEAF
      - EGG_ISMASTER=1
      # Active logs raw for debug?
      - EGG_LOG_RAW_IO=0
      # Need (re)generate the config file?
      - EGG_CONF_GENERATE=1
      # Need (re)generate the TLS?
      - EGG_TLS_GENERATE=1
      - EGG_TLS_REGENERATE=1
      - EGG_KEEP_NICK=1
      ### IRCD CONFIGURATION
      - IRC_NETNAME=Libera
      - IRC_SERVER=irc.libera.chat
        # IRCD PORT
          # without ssl: 6667
          # with ssl: +6697
      - IRC_PORT=+6697
        # PASSORD OF THE IRCD
      - IRC_PASSWORD=
        # List of salons to join
          # Example: #MyChannel1,#MyChannel2
      - IRC_CHANNELS=#docker-eggnet
      # Identify to services informations:
      - IRC_SERVICE_USER=EggNet
      - IRC_SERVICE_PASS=password
      ### PARTYLINE CONFIGURATION
      - PPL_USER=eggnet
      - PPL_PASS=rootegg
    container_name: "eggnet-master"
    restart: always
    volumes:
      - ${EGG_DIR_DATA:-./EGG_data}/:/eggdrop-data/data:rw
    ports:
      - "9090:3333"
    networks:
      - eggnet-network

  eggnet-slave:
    build:
      # PATH OF Dockerfile
      context: ../..
      args:
        ### The compilation options for eggdrop
        # Choice of eggdrop version
          # Branch/tags: develop, 1.9.1, ..
        - EGG_VERSION=dns.userfile
        # The URL of the git repository
        - EGG_URL=https://github.com/michaelortmann/eggdrop.git
        - PKG_EXTRA_RUNTIME=mysqltcl tcllib tcl-tls
    environment:
      ### EGGDROP CONFIGURATION
        # Bot irc Nickname
        # Your Nickname IRC
      - EGG_OWNER=ZarTek
      - EGG_ISMASTER=0
      ### IRCD CONFIGURATION
      - IRC_NETNAME=Libera
      - IRC_SERVER=irc.libera.chat
        # IRCD PORT
          # without ssl: 6667
          # with ssl: +6697
      - IRC_PORT=6667
      ### PARTYLINE CONFIGURATION
      - PPL_USER=eggnet
      - PPL_PASS=rootegg
    container_name: "eggnet-slave"
    restart: always
    volumes:
      - ${EGG_DIR_DATA:-./EGG_data}/:/eggdrop-data/data:rw
    ports:
      - "9091:3333"
    networks:
      - eggnet-network
networks:
  eggnet-network:
    driver: bridge
