  - uses: actions/checkout@v2
  - name: run shellcheck
    uses: sudo-bot/action-shellcheck@latest
    with:
        # https://github.com/koalaman/shellcheck#how-to-use
        cli-args: "app/startup-sequence/shell/*.sh"
